version: 0.2
# Cài đặt môi trường để CodeBuild có thể tương tác với AWS S3
phases:
  install:
    commands:
      # Lệnh này đảm bảo AWS CLI được cập nhật và có sẵn
      - echo "Running install phase..."
      - apt-get update && apt-get install -y awscli

  pre_build:
    commands:
      - echo "Running pre_build phase..."
      # Kiểm tra thư mục chứa tài liệu RAG tồn tại trong mã nguồn
      - |
        if [ ! -d "rag_documents" ]; then
          echo "Thư mục 'rag_documents' không tồn tại. Dừng quá trình đồng bộ."
          exit 1
        fi
      # Cài đặt biến môi trường cho tên S3 Bucket (nên được truyền từ CodePipeline)
      - RAG_S3_BUCKET_NAME="${RAGDocumentsS3Bucket}"
      - echo "Sẽ đồng bộ tài liệu đến S3 Bucket: $RAG_S3_BUCKET_NAME"

  build:
    commands:
      - echo "Running build phase (S3 Sync)..."
      # Lệnh quan trọng nhất: Đồng bộ tài liệu
      # --delete: Xóa các file trong S3 mà không còn tồn tại trong repo Git (giúp giữ S3 sạch sẽ)
      # --exact-timestamps: Chỉ đồng bộ khi file thay đổi thực sự
      - aws s3 sync --delete --exact-timestamps rag_documents/ s3://${RAG_S3_BUCKET_NAME}/

  post_build:
    commands:
      - echo "Đồng bộ tài liệu RAG hoàn tất."
      # BƯỚC TIẾP THEO QUAN TRỌNG: Kích hoạt Ingestion Lambda hoặc Bedrock Sync
      # Giả định: S3 Event sẽ tự động kích hoạt Ingestion Lambda sau khi đồng bộ.
      # Nếu bạn muốn kích hoạt thủ công trong CodeBuild:
      # - aws lambda invoke --function-name <TÊN_LAMBDA_INGESTION> --payload '{"action":"start_ingestion"}' response.json