AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CloudFormation stack for the Agent Code CI/CD Pipeline (Pipeline 1) 
  deploying the Containerized Agent to ECS/Fargate.

# =================================================================
# PARAMETERS & IMPORTS
# =================================================================
Parameters:
  ProjectName:
    Type: String
    Default: RAG-System
    Description: Project name used for importing values from other stacks.
  SourceRepoOwner:
    Type: String
    Description: Owner của GitHub repository chứa Dockerfile.
  SourceRepoName:
    Type: String
    Description: Tên GitHub repository.
  SourceRepoBranch:
    Type: String
    Default: main
  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub Personal Access Token.
  
  # Cần các tài nguyên mạng và ECS Cluster phải tồn tại
  ECSClusterName:
    Type: String
    Description: Name of the existing ECS Cluster.
  ECRRepositoryName: # Nơi chứa Docker Image Agent
    Type: String
    Description: Name of the ECR repository for the Agent image.
  PrivateSubnets: 
    Type: List
    Description: Danh sách Private Subnets IDs cho Fargate.
  AgentSecurityGroupId:
    Type: String
    Description: Security Group ID cho Fargate Task.

# =================================================================
# RESOURCES
# =================================================================
Resources:
  
  # -----------------------------------------------------------------
  # 1. IAM & Logging
  # -----------------------------------------------------------------
  
  # Role cho ECS Task để pull Image và ghi logs
  AgentTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: ecs-tasks.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

  # Log Group cho ECS Task
  AgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ProjectName}-Agent-Service"

  # -----------------------------------------------------------------
  # 2. ECS Task Definition & Service
  # -----------------------------------------------------------------
  
  # Task Definition
  AgentTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ProjectName}-Agent-Task"
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt AgentTaskExecutionRole.Arn
      # Sử dụng AgentRuntimeRole được Export từ File 2
      TaskRoleArn: !ImportValue !Sub "${ProjectName}-AgentRuntimeRoleArn" 
      ContainerDefinitions:
        - Name: agent-container-name 
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}:latest"
          Essential: true
          PortMappings:
            - ContainerPort: 8080 
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AgentLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
  
  # ECS Service
  AgentECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "${ProjectName}-Agent-Service"
      Cluster: !Ref ECSClusterName
      TaskDefinition: !Ref AgentTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED # PUBLIC từ agentcore.yaml
          Subnets: !Ref PrivateSubnets
          SecurityGroups: [!Ref AgentSecurityGroupId]

  # -----------------------------------------------------------------
  # 3. CodeBuild Project (Build Docker Image)
  # -----------------------------------------------------------------
  
  AgentDockerBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectName}-Agent-Docker-Build"
      # Sử dụng lại CodeBuildServiceRole được Export từ File 2
      ServiceRole: !ImportValue !Sub "${ProjectName}-CodeBuildServiceRoleArn" 
      Artifacts:
        Type: ARTIFACT_NAME
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0 
        PrivilegedMode: true # BẮT BUỘC cho Docker Build
        EnvironmentVariables:
          - Name: ECR_REPO_URI
            Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepositoryName}"
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${SourceRepoOwner}/${SourceRepoName}.git"
        Auth: { Type: OAUTH, Resource: !Ref GitHubToken }
        BuildSpec: file:buildspec-agent.yml # File này phải có trong Git Repo
  
  # -----------------------------------------------------------------
  # 4. CodePipeline (Source -> Build -> Deploy)
  # -----------------------------------------------------------------
  
  AgentCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub "${ProjectName}-Agent-Code-Deployment"
      # Sử dụng lại CodeBuildServiceRole được Export từ File 2
      RoleArn: !ImportValue !Sub "${ProjectName}-CodeBuildServiceRoleArn" 
      ArtifactStore:
        Type: S3
        Location: !Sub "codepipeline-${AWS::Region}-${AWS::AccountId}-artifacts"
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId: {Category: Source, Owner: ThirdParty, Provider: GitHub, Version: '1'}
              OutputArtifacts: [{Name: SourceArtifact}]
              Configuration: {Owner: !Ref SourceRepoOwner, Repo: !Ref SourceRepoName, Branch: !Ref SourceRepoBranch, OAuthToken: !Ref GitHubToken, PollForSourceChanges: 'false'}
        
        - Name: Build
          Actions:
            - Name: DockerBuild
              InputArtifacts: [{Name: SourceArtifact}]
              ActionTypeId: {Category: Build, Owner: AWS, Provider: CodeBuild, Version: '1'}
              OutputArtifacts: [{Name: BuildArtifact}]
              Configuration: {ProjectName: !Ref AgentDockerBuildProject}
        
        - Name: Deploy
          Actions:
            - Name: DeployECS
              ActionTypeId: {Category: Deploy, Owner: AWS, Provider: ECS, Version: '1'}
              InputArtifacts: [{Name: BuildArtifact}]
              Configuration:
                ClusterName: !Ref ECSClusterName
                ServiceName: !Ref AgentECSService.Name
                FileName: imagedefinitions.json