AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CloudFormation template to deploy the core RAG infrastructure:
  S3 Bucket, OpenSearch Serverless Collection/Index, and Bedrock Knowledge Base.

# =================================================================
# PARAMETERS
# =================================================================
Parameters:
  ProjectName:
    Type: String
    Default: RAG-System
    Description: Base name for all resources and Export names.

  EmbeddingModelArn:
    Type: String
    Default: arn:aws:bedrock:ap-southeast-1::foundation-model/amazon.titan-embed-text-v2:0
    Description: ARN of the Foundation Model used to create Embeddings.

  VectorStoreIndexName:
    Type: String
    Default: rag-vector-index
    Description: Name of the Index (Table) in OpenSearch.

  S3BucketNamePrefix:
    Type: String
    Default: rag-documents-store
    Description: Prefix for S3 Bucket name.

# =================================================================
# RESOURCES
# =================================================================
Resources:

  # -----------------------------------------------------------------
  # 1. S3 BUCKET
  # -----------------------------------------------------------------
  RAGDocumentsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${S3BucketNamePrefix}-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

  # -----------------------------------------------------------------
  # 2. OPENSEARCH SERVERLESS
  # -----------------------------------------------------------------

  # Encryption Security Policy (Required before creating collection)
  OpenSearchEncryptionPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: rag-system-encryption-policy
      Type: encryption
      Policy: !Sub |
        {
          "Rules": [
            {
              "ResourceType": "collection",
              "Resource": ["collection/rag-system-collection"]
            }
          ],
          "AWSOwnedKey": true
        }

  # Network Security Policy (Required for public access)
  OpenSearchNetworkPolicy:
    Type: AWS::OpenSearchServerless::SecurityPolicy
    Properties:
      Name: rag-system-network-policy
      Type: network
      Policy: !Sub |
        [
          {
            "Rules": [
              {
                "ResourceType": "collection",
                "Resource": ["collection/rag-system-collection"]
              }
            ],
            "AllowFromPublic": true
          }
        ]

  OpenSearchCollection:
    Type: AWS::OpenSearchServerless::Collection
    Properties:
      Name: rag-system-collection
      Type: VECTORSEARCH
    DependsOn:
      - OpenSearchEncryptionPolicy
      - OpenSearchNetworkPolicy

  # Data Access Policy - Grant permissions to Knowledge Base Role
  OpenSearchDataAccessPolicy:
    Type: AWS::OpenSearchServerless::AccessPolicy
    Properties:
      Name: rag-system-data-access-policy
      Type: data
      Policy:
        !Sub
          - |
            [
              {
                "Rules": [
                  {
                    "ResourceType": "index",
                    "Resource": ["index/rag-system-collection/*"],
                    "Permission": [
                      "aoss:CreateIndex",
                      "aoss:DescribeIndex",
                      "aoss:UpdateIndex",
                      "aoss:DeleteIndex",
                      "aoss:ReadDocument",
                      "aoss:WriteDocument"
                    ]
                  },
                  {
                    "ResourceType": "collection",
                    "Resource": ["collection/rag-system-collection"],
                    "Permission": [
                      "aoss:CreateCollectionItems",
                      "aoss:UpdateCollectionItems",
                      "aoss:DescribeCollectionItems"
                    ]
                  }
                ],
                "Principal": ["${KBRoleArn}"]
              }
            ]
          - {
              KBRoleArn: !GetAtt KnowledgeBaseServiceRole.Arn
            }
    DependsOn:
      - KnowledgeBaseServiceRole
      - OpenSearchCollection

  # -----------------------------------------------------------------
  # 3. IAM Role for Knowledge Base (Assume Role: bedrock.amazonaws.com)
  # -----------------------------------------------------------------
  KnowledgeBaseServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: KnowledgeBasePermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt RAGDocumentsS3Bucket.Arn
                  - !Sub "${RAGDocumentsS3Bucket.Arn}/*"
              - Effect: Allow
                Action:
                  - "aoss:APIAccessAll"
                Resource: !GetAtt OpenSearchCollection.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: !Ref EmbeddingModelArn

  # -----------------------------------------------------------------
  # 4. BEDROCK KNOWLEDGE BASE & DATA SOURCE
  # -----------------------------------------------------------------
  BedrockKnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Sub "${ProjectName}-KnowledgeBase"
      Description: !Sub "Knowledge Base for ${ProjectName} RAG System"
      RoleArn: !GetAtt KnowledgeBaseServiceRole.Arn
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Ref EmbeddingModelArn
      StorageConfiguration:
        Type: OPENSEARCH_SERVERLESS
        OpensearchServerlessConfiguration:
          CollectionArn: !GetAtt OpenSearchCollection.Arn
          VectorIndexName: !Ref VectorStoreIndexName
          FieldMapping:
            VectorField: vector
            TextField: text
            MetadataField: metadata
    DependsOn:
      - OpenSearchDataAccessPolicy
      - KnowledgeBaseServiceRole

  BedrockDataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      Name: !Sub "${ProjectName}-S3DataSource"
      Description: !Sub "S3 Data Source for ${ProjectName} Knowledge Base"
      KnowledgeBaseId: !Ref BedrockKnowledgeBase
      DataSourceConfiguration:
        Type: S3
        S3Configuration:
          BucketArn: !GetAtt RAGDocumentsS3Bucket.Arn
      VectorIngestionConfiguration:
        ChunkingConfiguration:
          ChunkingStrategy: FIXED_SIZE
          FixedSizeChunkingConfiguration:
            MaxTokens: 512
            OverlapPercentage: 20
    DependsOn:
      - BedrockKnowledgeBase

# =================================================================
# OUTPUTS - For cross-stack references and manual KB creation
# =================================================================
Outputs:
  RAGDocumentsS3BucketName:
    Description: S3 Bucket name for RAG documents
    Value: !Ref RAGDocumentsS3Bucket
    Export:
      Name: !Sub "${ProjectName}-RAGDocumentsS3BucketName"

  RAGDocumentsS3BucketArn:
    Description: S3 Bucket ARN for RAG documents
    Value: !GetAtt RAGDocumentsS3Bucket.Arn
    Export:
      Name: !Sub "${ProjectName}-RAGDocumentsS3BucketArn"

  OpenSearchCollectionArn:
    Description: OpenSearch Serverless Collection ARN
    Value: !GetAtt OpenSearchCollection.Arn
    Export:
      Name: !Sub "${ProjectName}-OpenSearchCollectionArn"

  OpenSearchCollectionEndpoint:
    Description: OpenSearch Serverless Collection Endpoint
    Value: !GetAtt OpenSearchCollection.CollectionEndpoint
    Export:
      Name: !Sub "${ProjectName}-OpenSearchCollectionEndpoint"

  KnowledgeBaseServiceRoleArn:
    Description: IAM Role ARN for Knowledge Base (use this when creating KB manually)
    Value: !GetAtt KnowledgeBaseServiceRole.Arn
    Export:
      Name: !Sub "${ProjectName}-KnowledgeBaseServiceRoleArn"

  VectorIndexName:
    Description: Vector index name to use for Knowledge Base
    Value: !Ref VectorStoreIndexName
    Export:
      Name: !Sub "${ProjectName}-VectorIndexName"

  KnowledgeBaseId:
    Description: Bedrock Knowledge Base ID
    Value: !Ref BedrockKnowledgeBase
    Export:
      Name: !Sub "${ProjectName}-KnowledgeBaseId"

  KnowledgeBaseArn:
    Description: Bedrock Knowledge Base ARN
    Value: !GetAtt BedrockKnowledgeBase.KnowledgeBaseArn
    Export:
      Name: !Sub "${ProjectName}-KnowledgeBaseArn"

  DataSourceId:
    Description: Bedrock Data Source ID
    Value: !Ref BedrockDataSource
    Export:
      Name: !Sub "${ProjectName}-DataSourceId"
